name: Keep Alive

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep alive
        run: echo "Keep alive $(date)"
